server:
  port: 8090

spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: Sina
    password: P1nkFl0yd1980#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20

#spring:
#  application:
#    name: notification
#  datasource:
#    url: jdbc:mysql://mysql:3307/notification
#    username: root
#    password: Sp@123456789
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false