spring:
  application:
    name: client

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5